### ISSUE TITLE
Incorrect Json format

### ISSUE THREAD

**Issue by garryde** [ethanosullivan/xml-to-json#9] opened 2022-04-20 15:01 UTC
I tried to use your service to convert the url below.

http://forex.ccb.com/cn/home/news/jshckpj_new.xml

https://api.factmaven.com/xml-to-json/?xml=http://forex.ccb.com/cn/home/news/jshckpj_new.xml

But the answer is not a standard JSON format.All keys are missing double quotes
<img width="656" alt="image" src="https://user-images.githubusercontent.com/14953698/164260985-3f639c4d-7269-4060-addb-b5164c808e5a.png">

**Comment by jinksraevan** [comment] 2022-04-21 20:56
Hi @garryde, I opened the same link that you provided and I don't see this issue on my end. I tested it out on Postman and my own browser (Brave).

![image](https://user-images.githubusercontent.com/23202467/164550965-be0abb56-dfde-45a1-87e5-818fe9483ed7.png)

Where are you viewing the output?

**Comment by jinksraevan** [comment] 2022-04-26 11:07
Closing this as it's not a bug on the API side.

**Closed as completed by jinksraevan** 2022-04-26 11:07 UTC
Labels: bug, invalid
